version: "3.8"
services:
  couchbase:
    image: couchbase:community-7.1.1
    ports:
      - 8091:8091
      - 11210:11210
    environment:
      - USERNAME=admin
      - PASSWORD=password
      - BUCKET_NAME=Backend_Bootcamp